{% set version = "2.8.1" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: 3e4a7e6ab35dd8a3e0182814c24e3f011eb683e4874f951cb7ecfc4b0f1bc5e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry >=1.3.1
    - poetry-core
    - poetry-dynamic-versioning
  run:
    - python >=3.8,<4.0
    - cartes >=0.7.4
    - requests >=2.27
    - requests_pkcs12 >=1.10
    - pyopenssl >=22.0
    - paramiko >=2.7
    - ipywidgets >=7.6
    - ipyleaflet >=0.17
    - pymodes >=2.14
    - openap >=1.1
    - metar >=1.8
    - click >=8.1
    - typing_extensions >=4.2
    - fastparquet >=0.7
    - onnxruntime >=1.12

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - traffic

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
