{% set version = "2.12" %}
{% set python_min = "3.10" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: da0e8fcb4b217a096a06c5862d8394228887bcc8f51c3fe33192253252f376d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - impunity >=1.0.5
    - pitot >=0.3.1
    - cartes >=0.8.2
    - pyopensky >=2.11
    - httpx >=0.27.2
    - ipywidgets >=7.6
    - ipyleaflet >=0.17
    - plotly >=5.22
    - rs1090 >=0.3.8
    - openap >=2.0
    - metar >=1.11.0
    - click >=8.1
    - typing-extensions >=4.12.2
    - pyarrow >=18.0.0
    - onnxruntime >=1.19.2
    - py7zr >=0.22.0
    - rich >=13.9.4

test:
  imports:
    - traffic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
