{% set version = "2.6.4" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: 21ba876dcde0891fce5dea33a6eae01681f3d21dd8620df507017b8f5ff540ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry >=1.0.10
    - poetry-core
  run:
    - python >=3.7
    - numpy >=1.18
    - scipy
    - matplotlib-base
    - pandas >=1.0.0
    - pyproj >=2.0
    - cartes >=0.2
    - shapely
    - requests
    - requests_pkcs12
    - appdirs
    - paramiko
    - typing_extensions
    - altair
    - ipywidgets
    - ipyleaflet
    - tqdm >=4.28
    - pymodes >=2.9
    - openap
    - pyarrow
    - beautifulsoup4
    - lxml
    - metar

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - traffic

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
