{% set version = "2.11.1" %}
{% set python_min = "3.10" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: b0532d12039fbf60fe14f469d9349ffac61ffe79dd0017d86ad65d16450ed4b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<2.0.0
    - impunity >=1.0.5
    - pitot >=0.3.1
    - cartes >=0.8.2
    - pyopensky >=2.11
    - httpx >=0.27.2
    - ipywidgets >=7.6
    - ipyleaflet >=0.17
    - plotly >=5.22
    - rs1090 >=0.3.8
    - openap >=2.0
    - metar >=1.11.0
    - click >=8.1
    - typing-extensions >=4.12.2
    - pyarrow >=18.0.0
    - onnxruntime >=1.19.2
    - py7zr >=0.22.0
    - rich >=13.9.4

test:
  imports:
    - traffic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
