{% set version = "2.6.4" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: 21ba876dcde0891fce5dea33a6eae01681f3d21dd8620df507017b8f5ff540ce

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry >=1.0.10
    - poetry-core
  run:
    - python >=3.7
    - numpy >=1.18
    - scipy >=1.7.0
    - matplotlib-base >=3.4.2
    - pandas >=1.0.0
    - pyproj >=2.0
    - cartopy >=0.19,<0.20
    - cartes >=0.3
    - shapely >=1.7.1
    - requests >=2.25.1
    - requests_pkcs12 >=1.10
    - appdirs >=1.4.4
    - paramiko >=2.7.2
    - typing_extensions >=3.10.0
    - altair >=4.1.0
    - ipywidgets >=7.6.3
    - ipyleaflet >=0.14.0
    - tqdm >=4.61.1
    - pymodes >=2.9
    - openap >=1.1
    - pyarrow >=4.0,<5.0
    - beautifulsoup4 >=4.9.3
    - lxml >=4.6.3
    - metar >=1.8.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - traffic

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
