{% set version = "2.10.2" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: 6a540a164fd110c95e91e1c90a2c286604e82386f2924748d75341dc97dc85ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<4.0
    - numpy >=1.26.4,<2.0.0
    - impunity >=1.0.4
    - pitot >=0.3.1
    - cartes >=0.7.6
    - pyopensky >=2.6
    - httpx >=0.26.0
    - ipywidgets >=7.6
    - ipyleaflet >=0.17
    - plotly >=5.22
    - rs1090 >=0.2.0
    - openap >=2.0
    - metar >=1.8
    - click >=8.1
    - typing-extensions >=4.2
    - pyarrow >=11.0.0
    - onnxruntime >=1.12

test:
  imports:
    - traffic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
