{% set version = "2.8.0" %}

package:
  name: traffic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traffic/traffic-{{ version }}.tar.gz
  sha256: 25bfe2435d4b9e2e341a1f3796dcf0ce822e0fda531afde693c80bf8dee821ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry >=1.0.10
    - poetry-core
  run:
    - python >=3.8,<4.0
    - numpy >=1.21,<2.0
    - scipy >=1.7,<2.0
    - matplotlib-base >=3.4.2,<4.0
    - pandas >=1.2.4,<2.0
    - pyproj >=3.1.0,<4.0
    - cartopy >=0.19.0,<1.0.0
    - cartes >=0.5,<1.0
    - shapely >=1.7.1,<1.8.1
    - requests >=2.25.1,<3.0
    - requests_pkcs12 >=1.10,<2.0
    - pyopenssl >=20.0,<21.0
    - appdirs >=1.4.4,<2.0
    - paramiko >=2.7.2,<3.0
    - typing_extensions >=4.2.0,<5.0.0
    - altair >=4.1.0,<5.0
    - ipywidgets >=7.6.3,<8.0
    - ipyleaflet >=0.14.0,<1.0.0
    - tqdm >=4.61.1,<5.0
    - pymodes >=2.9,<3.0
    - openap >=1.1,<2.0
    - pyarrow >=4.0
    - beautifulsoup4 >=4.9.3,<5.0
    - lxml >=4.6.3,<5.0
    - metar >=1.8.0,<2.0
    - rich >=11.2.0,<12.0.0
    - click >=8.1.2
    - onnxruntime >=1.10

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - traffic

about:
  home: https://github.com/xoolive/traffic
  license: MIT
  license_file: license.md
  summary: A toolbox for processing and analysing air traffic data
  doc_url: https://traffic-viz.github.io/

extra:
  recipe-maintainers:
    - xoolive
